[build]
  base = "/"
  command = "cd frontend && rm -rf node_modules package-lock.json && npm install --force && npm run build"
  publish = "frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
